# Generated by Django 2.2.16 on 2022-03-09 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='author',
            field=models.ForeignKey(on_delete=None, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Подписка на автора'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(on_delete=None, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Подпичсик'),
        ),
    ]
